filebeat.inputs:
  # AccountService (local + docker)
  - type: log
    paths:
      - /logs/accountservice-local/*/*.json
    fields:
      service: accountservice
      source_type: local
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /logs/accountservice/*/*.json
    fields:
      service: accountservice
      source_type: docker
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  # TransactionService
  - type: log
    paths:
      - /logs/transactionservice-local/*/*.json
    fields:
      service: transactionservice
      source_type: local
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /logs/transactionservice/*/*.json
    fields:
      service: transactionservice
      source_type: docker
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  # HistoryService
  - type: log
    paths:
      - /logs/historyservice-local/*/*.json
    fields:
      service: historyservice
      source_type: local
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /logs/historyservice/*/*.json
    fields:
      service: historyservice
      source_type: docker
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  # AuthServer
  - type: log
    paths:
      - /logs/authserver-local/*/*.json
    fields:
      service: authserver
      source_type: local
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /logs/authserver/*/*.json
    fields:
      service: authserver
      source_type: docker
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  # ApiGateway
  - type: log
    paths:
      - /logs/apigateway-local/*/*.json
    fields:
      service: apigateway
      source_type: local
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /logs/apigateway/*/*.json
    fields:
      service: apigateway
      source_type: docker
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true


# Send to Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "logs-%{[service]}-%{[source_type]}-%{+yyyy.MM.dd}"

# Config index template
setup.template.name: "logs"
setup.template.pattern: "logs-*"
